---
template:
  direction: Horizontal
  parts:
    - direction: Vertical
      borderless: true
      split_size:
        Fixed: 1
      run:
        plugin:
          location: "zellij:compact-bar"
    - direction: Vertical
      body: true
tabs:
  - direction: Vertical
session:
  name: "zellij"
  attach: true
