#!/usr/bin/env bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"


#down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

#boot picom or compton if it exists
if [ -x "$(command -v picom)" ]; then
  picom --experimental-backends &> /dev/null &
elif [ -x "$(command -v compton)" ]; then
  compton &> /dev/null &
fi

#set the theme.toml config
leftwm-command "LoadTheme $SCRIPTPATH/theme.toml"

index=0
monitor="$(polybar -m | grep +0+0 | sed s/:.*// | tac)"
leftwm-state -q -n -t $SCRIPTPATH/sizes.liquid | sed -r '/^\s*$/d' | while read -r width x y
do
  barname="mainbar$index"
  # monitor=$monitor offsetx=$x width=$width polybar -c $SCRIPTPATH/polybar/config.ini $barname &> /dev/null &
  monitor=$monitor offsetx=$x width=$width polybar -c $SCRIPTPATH/polybar/config.ini $barname &
  let index=index+1
done

